version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.sun.activation:jakarta.activation"
        versions: ">= 1.2.2"
